[project]
name = "sentinel"
version = "0.0.0"
dependencies = [
    "shodan",
    "dhooks",
    "nmap",
    "colorama",
    "cryptography",
    "hashcat",
    "protonvpn-cli",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
